/* The following code was generated by JFlex 1.3.5 on 11/23/17 5:05 PM */

/*-***
 *
 * This file defines a stand-alone lexical analyzer for a subset of the Pascal
 * programming language.  This is the same lexer that will later be integrated
 * with a CUP-based parser.  Here the lexer is driven by the simple Java test
 * program in ./PascalLexerTest.java, q.v.  See 330 Lecture Notes 2 and the
 * Assignment 2 writeup for further discussion.
 *
 */


import java_cup.runtime.*;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 11/23/17 5:05 PM from the specification file
 * <tt>file:/C:/Users/Zachary/Documents/School/COMP3200/pascal.jflex</tt>
 */
class PascalLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\11\1\6\25\0\1\11\1\53\5\0\1\5\1\44\1\45"+
    "\1\36\1\37\1\43\1\40\1\4\1\41\12\2\1\54\1\42\1\51"+
    "\1\50\1\52\2\0\32\1\1\46\1\0\1\47\1\0\1\3\1\0"+
    "\1\12\1\17\1\31\1\14\1\20\1\25\1\21\1\34\1\22\2\1"+
    "\1\23\1\30\1\13\1\26\1\27\1\1\1\15\1\24\1\33\1\32"+
    "\1\35\2\1\1\16\1\1\1\7\1\0\1\10\uff82\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    45,    90,   135,   180,   225,    45,   270,   315,   360, 
      405,   450,   495,   540,   585,   630,    45,    45,    45,    45, 
       45,    45,    45,    45,    45,    45,    45,   675,   720,   765, 
      810,   180,   855,   270,    45,   900,   945,   990,  1035,  1080, 
       90,    90,    90,  1125,  1170,  1215,  1260,    45,    45,    45, 
       45,    45,    90,  1305,  1350,    90,  1395,  1440,  1485,  1530, 
       90,  1575,  1620,    90,  1665,  1710,    90,    90,    90,    90, 
     1755,  1800,  1845,  1890,    90,  1935,  1980,    90
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\2\1\3\1\4\1\2\1\5\1\6\1\7\1\10"+
    "\1\2\1\7\1\11\4\3\1\12\1\13\1\3\1\14"+
    "\3\3\1\15\1\16\3\3\1\17\1\3\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\56\0\3\3"+
    "\6\0\24\3\21\0\1\4\1\0\1\40\52\0\1\40"+
    "\52\0\6\41\1\0\46\41\10\42\1\43\44\42\1\0"+
    "\3\3\6\0\1\3\1\44\1\3\1\45\20\3\20\0"+
    "\3\3\6\0\6\3\1\46\15\3\20\0\3\3\6\0"+
    "\1\3\1\47\7\3\1\50\12\3\20\0\3\3\6\0"+
    "\13\3\1\51\10\3\20\0\3\3\6\0\3\3\1\52"+
    "\7\3\1\53\10\3\20\0\3\3\6\0\3\3\1\54"+
    "\20\3\20\0\3\3\6\0\4\3\1\55\15\3\1\56"+
    "\1\3\20\0\3\3\6\0\1\57\23\3\67\0\1\60"+
    "\54\0\1\61\54\0\1\62\54\0\1\63\11\0\1\64"+
    "\50\0\3\3\6\0\2\3\1\65\21\3\20\0\3\3"+
    "\6\0\3\3\1\66\20\3\20\0\3\3\6\0\7\3"+
    "\1\67\14\3\20\0\3\3\6\0\2\3\1\70\21\3"+
    "\20\0\3\3\6\0\12\3\1\71\11\3\20\0\3\3"+
    "\6\0\14\3\1\72\7\3\20\0\3\3\6\0\15\3"+
    "\1\73\6\3\20\0\3\3\6\0\6\3\1\74\15\3"+
    "\20\0\3\3\6\0\3\3\1\75\20\3\20\0\3\3"+
    "\6\0\1\76\23\3\20\0\3\3\6\0\10\3\1\77"+
    "\13\3\20\0\3\3\6\0\6\3\1\100\15\3\20\0"+
    "\3\3\6\0\7\3\1\101\7\3\1\102\4\3\20\0"+
    "\3\3\6\0\6\3\1\103\15\3\20\0\3\3\6\0"+
    "\1\3\1\104\22\3\20\0\3\3\6\0\4\3\1\105"+
    "\17\3\20\0\3\3\6\0\1\3\1\106\22\3\20\0"+
    "\3\3\6\0\3\3\1\107\20\3\20\0\3\3\6\0"+
    "\6\3\1\110\15\3\20\0\3\3\6\0\1\111\23\3"+
    "\20\0\3\3\6\0\2\3\1\112\21\3\20\0\3\3"+
    "\6\0\16\3\1\113\5\3\20\0\3\3\6\0\20\3"+
    "\1\114\3\3\20\0\3\3\6\0\3\3\1\115\20\3"+
    "\20\0\3\3\6\0\6\3\1\116\15\3\17\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     1,  9,  1,  1,  1,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  1,  1,  1,  1,  1, 
     0,  0,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9, 
     9,  9,  9,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */

/**
 * Return a new Symbol with the given token id, and with the current line and
 * column numbers.
 */
Symbol newSym(int tokenId) {
    return new Symbol(tokenId, yyline, yycolumn);
}

/**
 * Return a new Symbol with the given token id, the current line and column
 * numbers, and the given token value.  The value is used for tokens such as
 * identifiers and numbers.
 */
Symbol newSym(int tokenId, Object value) {
    return new Symbol(tokenId, yyline, yycolumn, value);
}



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  PascalLexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  PascalLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[2025];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 116) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 2: 
        case 8: 
        case 9: 
        case 10: 
        case 11: 
        case 12: 
        case 13: 
        case 14: 
        case 15: 
        case 35: 
        case 36: 
        case 37: 
        case 38: 
        case 39: 
        case 43: 
        case 44: 
        case 45: 
        case 46: 
        case 53: 
        case 54: 
        case 56: 
        case 57: 
        case 58: 
        case 59: 
        case 61: 
        case 62: 
        case 64: 
        case 65: 
        case 70: 
        case 71: 
        case 72: 
        case 73: 
        case 75: 
        case 76: 
          {  return newSym(sym.IDENT, yytext());  }
        case 79: break;
        case 74: 
          {  return newSym(sym.PROGRAM);  }
        case 80: break;
        case 25: 
          {  return newSym(sym.RT_BRKT);  }
        case 81: break;
        case 19: 
          {  return newSym(sym.DIVIDE);  }
        case 82: break;
        case 47: 
          {  return newSym(sym.LESS_EQ);  }
        case 83: break;
        case 48: 
          {  return newSym(sym.GTR_EQ);  }
        case 84: break;
        case 49: 
          {  return newSym(sym.NOT_EQ);  }
        case 85: break;
        case 50: 
          {  return newSym(sym.ASSMNT);  }
        case 86: break;
        case 1: 
        case 5: 
        case 7: 
        case 29: 
          {  System.out.println("Illegal char, '" + yytext() +
                    "' line: " + yyline + ", column: " + yychar);  }
        case 87: break;
        case 31: 
          {  return newSym(sym.REAL, new Double(yytext()));  }
        case 88: break;
        case 34: 
          {  /* For this stand-alone lexer, print out comments. */
                  System.out.println("Recognized comment: " + yytext());  }
        case 89: break;
        case 27: 
          {  return newSym(sym.GTR);  }
        case 90: break;
        case 26: 
          {  return newSym(sym.EQ);  }
        case 91: break;
        case 22: 
          {  return newSym(sym.LEFT_PAREN);  }
        case 92: break;
        case 4: 
          {  return newSym(sym.DOT);  }
        case 93: break;
        case 40: 
          {  return newSym(sym.IF);  }
        case 94: break;
        case 41: 
          {  return newSym(sym.OR);  }
        case 95: break;
        case 42: 
          {  return newSym(sym.OF);  }
        case 96: break;
        case 52: 
          {  return newSym(sym.AND);  }
        case 97: break;
        case 55: 
          {  return newSym(sym.END);  }
        case 98: break;
        case 60: 
          {  return newSym(sym.VAR);  }
        case 99: break;
        case 77: 
          {  return newSym(sym.PROCEDURE);  }
        case 100: break;
        case 24: 
          {  return newSym(sym.LEFT_BRKT);  }
        case 101: break;
        case 23: 
          {  return newSym(sym.RT_PAREN);  }
        case 102: break;
        case 0: 
        case 3: 
          {  return newSym(sym.INT, new Integer(yytext()));  }
        case 103: break;
        case 69: 
          {  return newSym(sym.BEGIN);  }
        case 104: break;
        case 68: 
          {  return newSym(sym.ARRAY);  }
        case 105: break;
        case 21: 
          {  return newSym(sym.COMMA);  }
        case 106: break;
        case 20: 
          {  return newSym(sym.SEMI);  }
        case 107: break;
        case 16: 
          {  return newSym(sym.TIMES);  }
        case 108: break;
        case 17: 
          {  return newSym(sym.PLUS);  }
        case 109: break;
        case 18: 
          {  return newSym(sym.MINUS);  }
        case 110: break;
        case 28: 
          {  return newSym(sym.LESS);  }
        case 111: break;
        case 30: 
          {  return newSym(sym.COLON);  }
        case 112: break;
        case 63: 
          {  return newSym(sym.ELSE);  }
        case 113: break;
        case 66: 
          {  return newSym(sym.TYPE);  }
        case 114: break;
        case 67: 
          {  return newSym(sym.THEN);  }
        case 115: break;
        case 6: 
          {  /* Ignore whitespace. */  }
        case 116: break;
        case 51: 
          {  return newSym(sym.CHAR, new Character(yytext().charAt(1)));  }
        case 117: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
